### ISSUE TITLE
Bug Report: Misalignment of Column Names and Missing Column in "Data Semantics" Section

### ISSUE THREAD

**Issue by Pepesob** [cernopendata/cernopendata-portal#58]
While working on the "Data Semantics" section of a record in the Open Data portal, I noticed a bug. The column names in this section do not correspond to the actual content, and one of the columns is missing entirely. The attached image shows the issue from a custom record on my local instance of the Open Data portal:

![image](https://github.com/user-attachments/assets/18857d9d-b906-4bdf-832b-924fdc7de474)

Similar error can also be observed here [here](http://opendata.cern.ch/record/15009).

Upon investigating, I found the issue lies in the following lines of [code](https://github.com/cernopendata/cernopendata-portal/blob/dc02f93508e2ce4bdbe2cf5a34eb3df5d156c1fd/cernopendata/templates/cernopendata_records_ui/records/record_detail.html#L242-L264).

The problem lies in how the keys in the dictionary `record.dataset_semantics[0]` are handled. They are not in the same order as the values displayed, and the `unit` value is not displayed at all. This results in a disorganized table layout.

Another issue occurs when the first item in `record.dataset_semantics` does not have all fields defined. For instance, if the first item only defines `type`, `variable`, and `description`, but the second item includes `type`, `unit`, `variable`, and `description`, the `unit` column will not be displayed at all.

**Comment by Biscgit** [comment]
Hi Pepesob,
thank you for creating this well detailed issue, we are currently looking into it, and we will push a fix soon once it has been resolved.

**Comment by psaiz** [comment]
(reopening the issue that gets closed automatically when the PR gets merged).

**Comment by Biscgit** [comment]
Hi @Pepesob,
Thanks again for the bug report. We deployed the fixes for this issue recently. The column names are now correctly set, and all semantics fields are displayed as well, even when they are not defined as the first element. 
We are closing this issue since it has been resolved. If there are any follow-ups regarding this report, please feel free to re-open it.
Cheers, David
