### ISSUE TITLE
home page: introduce TOTEM logo and links

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-portal#67]
For the forthcoming release of TOTEM open data, we'd need to:

- introduce TOTEM logo in the page footer;
- add "About TOTEM" in the page header;
- add TOTEM to in the "Focus on" list on the home page.

Note that the release may happen very soon, so we may get ready to move it to PROD even before DELPHI and JADE, which may necessitate to prepare _also_ a special image including TOTEM logo only (without DELPHI and JADE).

**Comment by psaiz** [comment]
Dear @grzanka, I'm assigning this ticket to you, since this is related to https://github.com/cernopendata/opendata.cern.ch/issues/3690

The main thing that I need from you is the logo that should be included. Once we get that, I can take care of putting it in the correct place, and we can verify together how this will look like.

Could you please tell me which logo should I use?

**Comment by tiborsimko** [comment]
@psaiz You can take the TOTEM logo from https://totem-experiment.web.cern.ch/

**Comment by grzanka** [comment]
@tiborsimko here is a text which can be use in the `TOTEM about` part:

> TOTEM experiment: its journey and discovery
> 
> The TOTEM experiment is designed to explore the proton interactions when they survive intact after the collisions. On this respect, special detectors have been placed far from the interaction points to detect a small angle detection, due by elastic and inelastic interactions. This is why this physics is known as the 'forward' physics that inaccessible by the other LHC experiments.
> As CERN's 'longest' experiment, TOTEM detectors were spread across almost half a kilometre around the CMS interaction point. TOTEM had almost 3,000 kg of equipment, including four particle 'telescopes' as well as 26 'Roman pot' detectors.  
> The 'telescopes' – T1 and T2 – were cathode-strip chambers and Gas Electron Multipliers (GEM) to track the particles emerging from collisions at the CMS interaction point. Meanwhile, 'Roman Pots', named for their shape and first use by physicists from Rome in the 1970s, were performing measurements of scattered protons. 
> TOTEM data have been used to measure precisely the proton-proton cross section at different energies, from 900 GeV up to 13,6 TeV, either total, elastic and inelastic, giving also evidence of the existence of a gluon compound, called Odderon. The existence of such type of gluon compound is hidden in the QCD theory but was never seen before.
> With the forward telescopes TOTEM measured the track density at small angles giving a calibration for all the ultra-high energy cosmic rays experiments.
> Nowadays, TOTEM experiment has finished its measurement period and part of the hardware has been inherited by the CMS experiment and became the PPS (Protons Precision Spectrometer) forward detectors. In the transition period, TOTEM contributed in searches for beyond the standard model physics, such as anomalous quartic coupling with photons and dark matter.

**Comment by tiborsimko** [comment]
@grzanka Thanks, I have added the documentation page to the record pull request; we can iterate there. https://github.com/cernopendata/opendata.cern.ch/pull/3693

Here's how it currently looks:


![about-totem](https://github.com/user-attachments/assets/7353da49-a655-4dcd-8639-ca7929537356)

**Comment by grzanka** [comment]
@tiborsimko what you proposed in the PR looks good

**Comment by psaiz** [comment]
Deployed in production. Feel free to reopen (or create a new issue) if something is not as expected
