### ISSUE TITLE
ui: news links not working

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-portal#90]
### Current behaviour

1. Open news section on the home page: https://opendata-qa.cern.ch/#news
2. Click on a news item such as "DELPHI Collaboration releases its entire data collection".
3. Meet "Page not found" page.  (The link points to `/docs` even though the news page in question is `/docs/delphi-data-release-2024` and exists well on the portal.)

### Expected behaviour

Clicking on a news card should bring the user to the given news item that the card advertises.

**Comment by psaiz** [comment]
Deployed in production. Closing
